sudo: false

language: cpp

compiler:
    - clang
    - gcc

env:
    -
    - EXTRA_CMAKE_FLAGS='-DOPTIMIZATION=FALSE'
    - OMP_NUM_THREADS=1
    - OMP_NUM_THREADS=4

script:
    - cppcheck --error-exitcode=2 .
    - cmake "$EXTRA_CMAKE_FLAGS" .
    - make VERBOSE=1 check
    - ./memcheck.bash
    - bash -c './perceptualdiff | grep -i openmp'

after_success:
    - pip install --user cpp-coveralls
    - if [ "$CC" == "gcc" ];
      then PATH="$PATH:$HOME/.local/bin" ./coveralls.bash; fi

addons:
    apt:
        packages:
            - cmake
            - cppcheck
            - libfreeimage-dev
            - valgrind
