# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jbreiden/projects/pdiff/perceptualdiff-1.0.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jbreiden/projects/pdiff/perceptualdiff-1.0.1

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config /home/jbreiden/projects/pdiff/perceptualdiff-1.0.1/CPackConfig.cmake

# Special rule for the target package
package/fast: package

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config /home/jbreiden/projects/pdiff/perceptualdiff-1.0.1/CPackSourceConfig.cmake

# Special rule for the target package_source
package_source/fast: package_source

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbreiden/projects/pdiff/perceptualdiff-1.0.1/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbreiden/projects/pdiff/perceptualdiff-1.0.1/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named perceptualdiff

# Build rule for target.
perceptualdiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perceptualdiff

# fast build rule for target.
perceptualdiff/fast:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/build

# target to build an object file
CompareArgs.o:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/CompareArgs.o

# target to preprocess a source file
CompareArgs.i:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/CompareArgs.i

# target to generate assembly for a file
CompareArgs.s:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/CompareArgs.s

# target to build an object file
LPyramid.o:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/LPyramid.o

# target to preprocess a source file
LPyramid.i:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/LPyramid.i

# target to generate assembly for a file
LPyramid.s:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/LPyramid.s

# target to build an object file
Metric.o:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/Metric.o

# target to preprocess a source file
Metric.i:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/Metric.i

# target to generate assembly for a file
Metric.s:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/Metric.s

# target to build an object file
PerceptualDiff.o:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/PerceptualDiff.o

# target to preprocess a source file
PerceptualDiff.i:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/PerceptualDiff.i

# target to generate assembly for a file
PerceptualDiff.s:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/PerceptualDiff.s

# target to build an object file
RGBAImage.o:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/RGBAImage.o

# target to preprocess a source file
RGBAImage.i:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/RGBAImage.i

# target to generate assembly for a file
RGBAImage.s:
	$(MAKE) -f CMakeFiles/perceptualdiff.dir/build.make CMakeFiles/perceptualdiff.dir/RGBAImage.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... perceptualdiff"
	@echo "... rebuild_cache"
	@echo "... CompareArgs.o"
	@echo "... CompareArgs.i"
	@echo "... CompareArgs.s"
	@echo "... LPyramid.o"
	@echo "... LPyramid.i"
	@echo "... LPyramid.s"
	@echo "... Metric.o"
	@echo "... Metric.i"
	@echo "... Metric.s"
	@echo "... PerceptualDiff.o"
	@echo "... PerceptualDiff.i"
	@echo "... PerceptualDiff.s"
	@echo "... RGBAImage.o"
	@echo "... RGBAImage.i"
	@echo "... RGBAImage.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

