.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PERCEPTUALDIFF 1 "September 28, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
perceptualdiff \- compare images using a perceptually based image metric
.SH SYNOPSIS
.B perceptualdiff
.RI [ options ] " <image1> <image2>"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B perceptualdiff
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBperceptualdiff\fP is a program that compares image1.tif and 
image2.tif using a perceptually based image metric. Note: Input 
files can also be in the PNG format
.SH OPTIONS
A summary of options is included below.
.TP
.B \-verbose
Turns on verbose mode
.TP
.B \-fov <deg>
Field of view in degrees (0.1 to 89.9)
.TP
.B \-threshold <p>
#pixels p below which differences are ignored
.TP
.B \-gamma <g>
Value to convert rgb into linear space (default 2.2)
.TP
.B \-luminance <l>
 White luminance (default 100.0 cdm^-2)
.TP
.B \-output <o.ppm>
 Write difference to the file o.ppm
.br
.SH AUTHOR
perceptualdiff was written by Yangli Hector Yee <yeehector@users.sourceforge.net>
.PP
This manual page was written by Jeff Breidenbach <jab@debian.org>,
for the Debian project (but may be used by others).
